sonar.projectKey=flying-tea-squad_lms
sonar.organization=flying-tea-squad
sonar.host.url=https://sonarcloud.io
sonar.projectVersion=1.0

# Source and test paths
sonar.sources=src/main/java
sonar.tests=src/test/java

# Compiled classes directory
sonar.java.binaries=target/classes

# Code coverage report path (Jacoco)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
