-- Migration V5: Create missing tables for lesson completion, monitoring alerts, performance summaries, and pipeline logs

CREATE TABLE IF NOT EXISTS lesson_completion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    lesson_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    completion_date TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'COMPLETED',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lesson_completion_student FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_completion_lesson FOREIGN KEY (lesson_id) REFERENCES course_lesson(id) ON DELETE CASCADE,
    CONSTRAINT fk_lesson_completion_course FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE,
    CONSTRAINT uk_student_lesson_completion UNIQUE (student_id, lesson_id)
);

CREATE INDEX IF NOT EXISTS idx_completion_student_course ON lesson_completion(student_id, course_id);
CREATE INDEX IF NOT EXISTS idx_completion_student_lesson ON lesson_completion(student_id, lesson_id);

CREATE TABLE IF NOT EXISTS performance_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id VARCHAR(64) NOT NULL UNIQUE,
    report_type VARCHAR(30) NOT NULL,
    entity_id BIGINT NOT NULL,
    entity_name VARCHAR(255),
    date_generated TIMESTAMP NOT NULL,
    total_students INT,
    total_lessons INT,
    completed_lessons INT,
    completion_rate DOUBLE PRECISION,
    attendance_rate DOUBLE PRECISION,
    engagement_score DOUBLE PRECISION,
    metrics_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_report_type_entity ON performance_summary (report_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_date_generated ON performance_summary (date_generated);

CREATE TABLE IF NOT EXISTS monitoring_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id VARCHAR(64) NOT NULL UNIQUE,
    severity VARCHAR(20) NOT NULL,
    component VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    message VARCHAR(1000),
    metric_value DOUBLE PRECISION,
    threshold_value DOUBLE PRECISION,
    acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_alert_severity ON monitoring_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_alert_created ON monitoring_alerts (created_at);
CREATE INDEX IF NOT EXISTS idx_alert_ack ON monitoring_alerts (acknowledged);

CREATE TABLE IF NOT EXISTS pipeline_execution_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name VARCHAR(100) NOT NULL,
    execution_status VARCHAR(30) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    duration_ms BIGINT,
    records_processed BIGINT,
    error_message VARCHAR(1000),
    freshness_timestamp TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pipeline_name_start ON pipeline_execution_log (pipeline_name, start_time);
CREATE INDEX IF NOT EXISTS idx_pipeline_status ON pipeline_execution_log (execution_status);
